# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontrolio < Formula
  desc "Time tracking through your CLI."
  homepage "https://kontrolio.com/"
  version "0.0.51"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcelovicentegc/kontrolio/releases/download/v0.0.51/kontrolio_0.0.51_darwin_amd64.tar.gz"
      sha256 "8de743030ef64db327051b77c77876b5ea6250ae71d90a92610d71a5ab883af7"

      def install
        bin.install "kontrolio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marcelovicentegc/kontrolio/releases/download/v0.0.51/kontrolio_0.0.51_linux_amd64.tar.gz"
      sha256 "528b6c4717b6116e5bef1b0e432d592795a30b4c51c68beb9a66ee1201558622"

      def install
        bin.install "kontrolio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcelovicentegc/kontrolio/releases/download/v0.0.51/kontrolio_0.0.51_linux_arm64.tar.gz"
      sha256 "d76305e835b10295ff1a79454e337ff72150aba27c894d15e5d54c61af4452b6"

      def install
        bin.install "kontrolio"
      end
    end
  end

  test do
    system "#{bin}/kontrolio --version"
  end
end
