# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontrolio < Formula
  desc ""
  homepage ""
  version "0.0.48"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcelovicentegc/kontrolio/releases/download/v0.0.48/kontrolio_0.0.48_darwin_amd64.tar.gz"
      sha256 "3aef704b4b3b021b16b6961a4bcf7976c6915f27c8026248a22dd9683e8bae45"

      def install
        bin.install "kontrolio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcelovicentegc/kontrolio/releases/download/v0.0.48/kontrolio_0.0.48_linux_arm64.tar.gz"
      sha256 "dfe0bb1e188d45d16c07f70c6e7cc333c7fede660c4ed5dd860bc3cb5c898235"

      def install
        bin.install "kontrolio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcelovicentegc/kontrolio/releases/download/v0.0.48/kontrolio_0.0.48_linux_amd64.tar.gz"
      sha256 "eb4b9f1276ccd7b63dbcd6499e408c0c9486f35455e682366a47afc6ebcb53dd"

      def install
        bin.install "kontrolio"
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
